### ISSUE TITLE
dbt Power User does not work

### ISSUE THREAD

**Issue by ausiddiqui** [AltimateAI/vscode-dbt-power-user#1402]
### Expected behavior

To have models appear

### Actual behavior

None of the models appear

### Steps To Reproduce

Went through setup and configuration and running the Start Scan produces this error. This is just a docs file where I don't specify the YAML version: 2. My main dbt_project.yml has config-version: 2 set though.

### Log output/Screenshots

dbt configuration is invalid : Compilation Error
  The yml property file at models/staging/my_model/_docs/stg_mod__variable.yml is invalid because the yml property file models/staging/my_model/_docs/stg_mod__variable.yml  is missing a version tag. Please consult the documentation for more information on yml property file syntax:
  
  https://docs.getdbt.com/reference/configs-and-properties

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/e382068d-a813-46b9-aa31-cbad8c2fabeb">

### Operating System

macOS 14.6.1

### dbt version

1.4.5

### dbt Adapter

n/a

### dbt Power User version

v0.44.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by manarbenradi** [comment]
i have the same issue

**Comment by anandgupta42** [comment]
@manarbenradi is this still an issue?

**Comment by GerritPlehn** [comment]
@anandgupta42 experiencing the same issue here. power user v0.44.7, vscode v1.93.0

**Comment by anandgupta42** [comment]
@GerritPlehn What version of dbt are you using?

**Comment by t8rohman** [comment]
got a same issue here!

**Comment by GerritPlehn** [comment]
@anandgupta42 Experiencing the issue both on dbt 1.8.4 and 1.8.6. Please let me know if you need any other info.

**Comment by anandgupta42** [comment]
@GerritPlehn We need help debugging the issue. Can you drop us a message here https://app.myaltimate.com/contactus ?

**Comment by jackhulbertpdx** [comment]
Having the same issue on config-version: 2

**Comment by GerritPlehn** [comment]
@anandgupta42 I've dropped a message in your chat. 
I've figured something out though: the issue seems to be related to the selected Python interpreter.
Unfortunately I didn't take care to note what the selected interpreter was when experiencing the issue, but I've changed it to my venv interpreter using 
`> Python: Select Interpreter` 

I can't seem to replicate the error either by switching back to the other available interpreters.

**Comment by OneCyrus** [comment]
same issue here. also can see that the extension can't find a dbt project (no select project warning). downgrading to an older dbt power user extension version fixes the issue here.

**Comment by anandgupta42** [comment]
@OneCyrus which version did you downgrade to?

**Comment by OneCyrus** [comment]
@anandgupta42 v0.44.5 - it's the last version which worked here

**Comment by mdesmet** [comment]
`The yml property file at models/staging/my_model/_docs/stg_mod__variable.yml is invalid because the yml property file models/staging/my_model/_docs/stg_mod__variable.yml is missing a version tag. Please consult the documentation for more information on yml property file syntax:`

I was able to repro this issue on the mentioned dbt version (1.4). Just adding `version: 2` in the mentioned file fixes the issue. This is not an extension issue, but just a dbt error, following the advice from the error resolves the issue. I will close this issue, please reopen if you think this explanation is incorrect.
