### ISSUE TITLE
DBT project not loading

### ISSUE THREAD

**Issue by FDG4663** [AltimateAI/vscode-dbt-power-user#1405]
### Expected behavior

I can use Power User for dbt features in VS Code

### Actual behavior

the extension does not load, nor show error messages. all functions and tasks related to the method are nop (do nothing)

### Steps To Reproduce

Power User has been working today (earlier), but after restarting VSCode it stopped working

### Operating System

Windows 11

### dbt version

1.8.0

### dbt Adapter

dbt cloud

### dbt Power User version

0.44.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by FDG4663** [comment]
It seems that downgrading the Python **extension** fixes the issue
not working => Python v2024.14.0
working => Python v2024.12.3

**Comment by anandgupta42** [comment]
@FDG4663 It is indeed related to that. The latest version of the Python extension released a backward incompatible change, forcing a dependency upgrade to VSCode 1.91 or beyond. The only way to get around the problem is either upgrading to the latest version of vscode or downgrading the python extension.

more details can be found [here](https://github.com/AltimateAI/vscode-dbt-power-user/issues/1334#issuecomment-2338774831)
