### ISSUE TITLE
Execute dbt SQL not working 

### ISSUE THREAD

**Issue by antoine-lefebvre** [AltimateAI/vscode-dbt-power-user#1429]
### Expected behavior

When I click on the execute dbt SQL button, the results are displayed

### Actual behavior

When I click on the execute dbt SQL button I get the following error:

> Database Error
> Syntax error: Unexpected keyword LIMIT at [4:3]

Followed by:

```
{
  "code": -1,
  "message": "Database Error\n  Syntax error: Unexpected keyword LIMIT at [4:3]",
  "data": "\"Error: Database Error\\n  Syntax error: Unexpected keyword LIMIT at [4:3]\\n\\tat DBTCoreProjectIntegration_1.<anonymous> (/home/vscode/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.39.20/dist/extension.js:18410:127)\\n\\tat Generator.throw (<anonymous>)\\n\\tat rejected (/home/vscode/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.39.20/dist/extension.js:26056:28)\""
}
```
and I can see in my BigQuery query history that were 2 queries sent with just:
```
LIMIT 500 
```
and nothing else in the query

### Steps To Reproduce

- Open a dbt model
- Click on the execute dbt SQL button
- See the error

### Log output/Screenshots

![image](https://github.com/user-attachments/assets/13911229-c696-4a94-8f10-f86d9ef30d3a)

### Operating System

macos version 14.6.1

### dbt version

1.8.6

### dbt Adapter

dbt-bigquery

### dbt Power User version

v0.45.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@antoine-lefebvre, does this happen for all queries or specific ones?

**Comment by yoppysource** [comment]
Same here, it works well but when I add limit keyword it falls to fail. I am using dbt-bigquery as well!

**Comment by mdesmet** [comment]
Yeah, that seems a bug in dbt or the adapter

```
❯ dbt show -m customers
06:12:32  Running with dbt=1.8.0
06:12:33  Registered adapter: bigquery=1.8.0
06:12:33  Found 10 models, 3 seeds, 20 data tests, 2 sources, 478 macros
06:12:33  
06:12:34  Concurrency: 4 threads (target='dev')
06:12:34  
06:12:35  BigQuery adapter: https://console.cloud.google.com/bigquery?project=diesel-command-384802&j=bq:US:437bfd04-56d9-41dd-99e2-c60614642672&page=queryresults
06:12:35  Encountered an error:
Runtime Error
  Database Error in model customers (models/customers.sql)
    Syntax error: Expected end of input but got keyword LIMIT at [74:3]
```

**Comment by antoine-lefebvre** [comment]
> @antoine-lefebvre, does this happen for all queries or specific ones?

This happens for all queries as far I as can tell

**Comment by pmags** [comment]
I also started with this issue out of the blue. No matter how i change the query template in the settings it allways previews SQL server using select * from ({query}) as query limit {limit} which for sql server will never run. in the past we used to change the template for {query} order by 1 OFFSET 0 ROWS FETCH FIRST {limit} ROWS ONLY to run sql server. But i believe this is not required for newer versions.

Also i am running inside a devcontainer.

**Comment by VVillereyAmo** [comment]
Hello, I have a bug too. I don't store it on BigQuery; maybe it's an explanation? 

`limit 500 
BigQuery adapter: https://console.cloud.google.com/bigquery?project=toto-extractors-sbx&j=bq:US:tata&page=queryresults
BigQuery adapter: Retry attempt 1 of 1 after error: BadRequest('Syntax error: Unexpected keyword LIMIT at [55:3]; reason: invalidQuery, location: query, message: Syntax error: Unexpected keyword LIMIT at [55:3]')
BigQuery adapter: https://console.cloud.google.com/bigquery?project=toto-extractors-sbx&j=bq:US:titi9&page=queryresults
BigQuery adapter: https://console.cloud.google.com/bigquery?project=toto-extractors-sbx&j=bq:US:titi9&page=queryresults
Database Error in test is_zero_open_or_closed_store (tests/is_zero_open_or_closed_store.sql) Syntax error: Unexpected keyword LIMIT at [55:3]
Finished running node test.toto.is_zero_open_or_closed_store
Marking all children of 'test.toto.is_zero_open_or_closed_store' to be skipped because of status 'error'. Reason: Database Error in test is_zero_open_or_closed_store (tests/is_zero_open_or_closed_store.sql) Syntax error: Unexpected keyword LIMIT at [55:3].
`
