### ISSUE TITLE
Run arbitrary SQL

### ISSUE THREAD

**Issue by bramrodenburg** [AltimateAI/vscode-dbt-power-user#810]
### Describe the feature

It would be nice if it were possible to directly run (dbt) SQL from a draft (an unsaved file) in VSCode. I often find myself wanting to quickly execute a piece of SQL to check a few things in the data. To do this, I either have to save the file first (which I don't want to) and then run it with dbt power user, or I have to use a different plugin (e.g. sqltools) but this gives me a completely different user experience.

### Describe alternatives you've considered

In VSCode the sqltools plugin, though this gives a different experience than the VSCode dbt Power User plugin.

### Who will benefit?

Everyone that wants to run SQL without saving it to a file.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by OneCyrus** [comment]
we would welcome this feature. there are quite some queries we would like to execute which don't result in a pure table.

thins like running explain/analyze queries or just some materializing queries. currently they all break because the extension adds the "limit" syntax which only works for pure queries.

it would be great if the result could be shown in a pure console style output when not returning table results (e.g. query plan)
