### ISSUE TITLE
targetPathOverride configuration no longer being honored by the dbt invocation

### ISSUE THREAD

**Issue by jsnb-devoted** [AltimateAI/vscode-dbt-power-user#843]
### Expected behavior

I have this setting in my workspace:
```
"dbt.targetPathOverride": "${workspaceFolder}/data/dbt/target_power_user",
```
I would expect the extension to create that directory and put the dbt artifact files (manifest, partial_parse, etc) in it.

### Actual behavior

It looks like the extension is falling back to the default or the `DBT_TARGET_DIR` environment variable. Since the extension uses a different target than the typical runs it is overwriting the manifest/partial parse files and causing dbt runs to do a full parse every time the extension reparses the project.

### Steps To Reproduce

Reload the window and watch the files generated in the target directory

### Operating System

Ubuntu 22.04.3 LTS

### dbt version

1.6

### dbt Adapter

snowflake

### dbt Power User version

0.29.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by robertoash** [comment]
From what I can see these two settings were removed by @mdesmet in [this PR](https://github.com/AltimateAI/vscode-dbt-power-user/pull/880/files):
- dbt.profilesDirOverride
- dbt.targetPathOverride

Now, the extension uses this logic to determine paths: https://github.com/AltimateAI/vscode-dbt-power-user/pull/880#pullrequestreview-1866303455

I don't fully understand why this was done but I am trying to figure out a way to set the env variable only for the workspace since I don't want to have a system-wide env variable in my .zshrc that needs to be managed. 

I'm using direnv but that doesn't help (maybe because the extension loads before direnv has had time to load the env variable?).

**Comment by anandgupta42** [comment]
Hey @jsnb-devoted - Please close the issue once you have verified the fix

**Comment by anandgupta42** [comment]
@robertoash The "targetPath" feature has been [deprecated by dbt in v1.5](https://docs.getdbt.com/reference/project-configs/target-path), and since we had an override built into the extension, it could have caused issues when the feature is finally removed. To avoid these kinds of issues in the future, we decided to use the default dbt ENV variable settings. That's also why we made "profilesDirOverride" an env variable as well.

As far as environment variables are concerned, we have multiple ways of setting it - https://docs.myaltimate.com/setup/optConfig/

**Comment by jsnb-devoted** [comment]
I confirmed this was fixed. I prefer the terminal env variables override experience so this is all good. I'm the one that implemented the `targetPathOverride` config and I think it was because setting the  target/profile in `terminal.integrated.env` previously didn't work. All good over here -- thanks so much @mdesmet and @anandgupta42

**Comment by kiwamizamurai** [comment]
@jsnb-devoted 

```json
{
    "terminal.integrated.env.osx": {
        "DBT_PROFILES_DIR": "${workspaceFolder}/dbt",
        "DBT_TARGET_PATH": "${workspaceFolder}/dbt"
    },
    "dbt.targetPathOverride": "${workspaceFolder}/dbt/target",
}
```

I think that it does not work.
- dbt version 1.7.6

**Comment by anandgupta42** [comment]
@kiwamizamurai What's the version of extension are you on?

**Comment by kiwamizamurai** [comment]
@anandgupta42 

> What's the version of extension are you on?

sorry, version is v0.36.4

> Also, did you restart vscode after applying these settings?

Yes, I did.


And I can not find targetPathOverride section with this UI
<img width="1233" alt="スクリーンショット 2024-03-26 12 53 40" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/24860100/c6d8e974-5f35-48eb-b3f2-7a22246409ed">
